### ISSUE TITLE
Module doesn't function....

### ISSUE THREAD

**Issue by ghost** [ghoneycutt/puppet-module-nfs#48] opened 2015-05-08 19:12 UTC
Hello:

The error I receive is this:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: can't modify frozen string at /etc/puppetlabs/puppet/environments/development/modules/nfs/manifests/idmap.pp:27

I'm on PE 3.7

Please let me know if I'm not setting something correctly.

Thanks
Joey

**Comment by ghoneycutt** [comment] 2015-05-08 19:53
What version of stdlib do you have? This seems to be an issue with the `is_domain_name()` function. How are you calling this class? Just `include nfs` or calling it directly? Are you calling it with the parameterized class syntax such as `class { 'nfs::idmap': }` ? If you are using Hiera, could you send me anything related to the nfs module.

**Comment by ghoneycutt** [comment] 2015-05-08 19:54
What is the output of `puppet config print parser` ? What is the version of Puppet `puppet --version` ?

**Comment by jkarns87** [comment] 2015-05-08 20:00
Hello Garrett:

I use Roles and Profiles, so this is what I had.
---------------------------------------------------
class profile::nfs {
  include nfs
  class nfs::idmap {
    ldap_server => 'our.ldap.server.edu'
    ldap_base   => 'dc=server,dc=edu'
  }
}
-------------------------------------------------
class role::new_role {
  include profile::nfs
}
------------------------------------------------

stdlib version - Supported Release 4.5.1
puppet config print parser -> outputs -> "current"

# puppet --version
3.7.4 (Puppet Enterprise 3.7.2)

Thanks
Joey

**Comment by ghoneycutt** [comment] 2015-05-11 18:34
I was not able to reproduce. Did notice you have a typo in your code, should be.

``` puppet
  class { 'nfs::idmap':
    ldap_server => 'our.ldap.server.edu',
    ldap_base   => 'dc=server,dc=edu',
  }
```
What is your osfamily? on EL, the inclusion of the `nfs` class will automatically include the `nfs::idmap` class, so if you want to specify ldap_server and ldap_base, then you would specify those values in hiera, such as.

``` yaml
nfs::idmap::ldap_server: 'our.ldap.server.edu'
nfs::idmap::ldap_base: 'dc=server,dc=edu'
```

**Comment by ghoneycutt** [comment] 2017-08-30 02:51
Closing issue, please re-open if after using the latest versions this is still an issue.

**Closed by ghoneycutt** 2017-08-30 02:51 UTC
